#docker-compose build
version: '3'

services:

  db:
    image: kartoza/geoserver:2.23.0
    container_name: geoserver
    volumes:
      - $HOME/geoserver_data:/opt/geoserver/data_dir/
    environment:
      - SSL=true
      - EXISTING_DATA_DIR=true
      - SAMPLE_DATA=false
      - STABLE_EXTENSIONS=charts-plugin,db2-plugin,css-plugin
    ports:
      - "8100:8080"
      - "1443:8443"
    restart: on-failure
    healthcheck:
      test: "exit 0"
